name: drive_demo
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  after_layout: ^1.2.0
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.14.0
  firebase_core: ^2.22.0
  flutter:
    sdk: flutter
  get: ^4.6.6
  google_sign_in: ^6.1.6
  googleapis: ^11.4.0
  googledrivehandler: ^1.0.5
  http: ^1.1.0
  path_provider: ^2.1.1

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
